// @generated by protoc-gen-es v2.14.0 with parameter "target=ts"
// @generated from file proto/management/v1/agents.proto (package graphene.management.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/management/v1/agents.proto.
 */
export const file_proto_management_v1_agents: GenFile = /*@__PURE__*/
  fileDesc("CiBwcm90by9tYW5hZ2VtZW50L3YxL2FnZW50cy5wcm90bxIWZ3JhcGhlbmUubWFuYWdlbWVudC52MSI3CgpQdHlSZXF1ZXN0Eg0KBWFnZW50GAEgASgJEgwKBGNvbHMYAiABKA0SDAoEcm93cxgDIAEoDSLkAQoIUHR5Q2h1bmsSOQoGb3BlbmVkGAEgASgLMicuZ3JhcGhlbmUubWFuYWdlbWVudC52MS5QdHlDaHVuay5PcGVuZWRIABIOCgRkYXRhGAIgASgMSAASOQoGY2xvc2VkGAMgASgLMicuZ3JhcGhlbmUubWFuYWdlbWVudC52MS5QdHlDaHVuay5DbG9zZWRIABocCgZPcGVuZWQSEgoKc2Vzc2lvbl9pZBgBIAEoCRosCgZDbG9zZWQSEQoJZXhpdF9jb2RlGAEgASgFEg8KB21lc3NhZ2UYAiABKAlCBgoEYm9keSK2AQoPUHR5SW5wdXRSZXF1ZXN0EhIKCnNlc3Npb25faWQYASABKAkSDgoEZGF0YRgCIAEoDEgAEkAKBnJlc2l6ZRgDIAEoCzIuLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuUHR5SW5wdXRSZXF1ZXN0LlJlc2l6ZUgAEg8KBWNsb3NlGAQgASgISAAaJAoGUmVzaXplEgwKBGNvbHMYASABKA0SDAoEcm93cxgCIAEoDUIGCgRib2R5IhIKEFB0eUlucHV0UmVzcG9uc2UyuQEKCUFnZW50c0FQSRJNCgNQdHkSIi5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLlB0eVJlcXVlc3QaIC5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLlB0eUNodW5rMAESXQoIUHR5SW5wdXQSJy5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLlB0eUlucHV0UmVxdWVzdBooLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuUHR5SW5wdXRSZXNwb25zZUJGWkRnaXRodWIuY29tL2dyYXBoZW5lLWNpL2dyYXBoZW5lL3BrZy9wcm90by9tYW5hZ2VtZW50L3YxO21hbmFnZW1lbnR2MWIGcHJvdG8z");

/**
 * @generated from message graphene.management.v1.PtyRequest
 */
export type PtyRequest = Message<"graphene.management.v1.PtyRequest"> & {
  /**
   * Agent is the machine's record id ("edge-1").
   *
   * @generated from field: string agent = 1;
   */
  agent: string;

  /**
   * @generated from field: uint32 cols = 2;
   */
  cols: number;

  /**
   * @generated from field: uint32 rows = 3;
   */
  rows: number;
};

/**
 * Describes the message graphene.management.v1.PtyRequest.
 * Use `create(PtyRequestSchema)` to create a new message.
 */
export const PtyRequestSchema: GenMessage<PtyRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_agents, 0);

/**
 * @generated from message graphene.management.v1.PtyChunk
 */
export type PtyChunk = Message<"graphene.management.v1.PtyChunk"> & {
  /**
   * @generated from oneof graphene.management.v1.PtyChunk.body
   */
  body: {
    /**
     * Opened is the first chunk: the session id every PtyInput names.
     *
     * @generated from field: graphene.management.v1.PtyChunk.Opened opened = 1;
     */
    value: PtyChunk_Opened;
    case: "opened";
  } | {
    /**
     * Data is raw shell output, escape sequences included.
     *
     * @generated from field: bytes data = 2;
     */
    value: Uint8Array;
    case: "data";
  } | {
    /**
     * Closed is the last chunk: how the shell ended.
     *
     * @generated from field: graphene.management.v1.PtyChunk.Closed closed = 3;
     */
    value: PtyChunk_Closed;
    case: "closed";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message graphene.management.v1.PtyChunk.
 * Use `create(PtyChunkSchema)` to create a new message.
 */
export const PtyChunkSchema: GenMessage<PtyChunk> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_agents, 1);

/**
 * @generated from message graphene.management.v1.PtyChunk.Opened
 */
export type PtyChunk_Opened = Message<"graphene.management.v1.PtyChunk.Opened"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;
};

/**
 * Describes the message graphene.management.v1.PtyChunk.Opened.
 * Use `create(PtyChunk_OpenedSchema)` to create a new message.
 */
export const PtyChunk_OpenedSchema: GenMessage<PtyChunk_Opened> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_agents, 1, 0);

/**
 * @generated from message graphene.management.v1.PtyChunk.Closed
 */
export type PtyChunk_Closed = Message<"graphene.management.v1.PtyChunk.Closed"> & {
  /**
   * @generated from field: int32 exit_code = 1;
   */
  exitCode: number;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message graphene.management.v1.PtyChunk.Closed.
 * Use `create(PtyChunk_ClosedSchema)` to create a new message.
 */
export const PtyChunk_ClosedSchema: GenMessage<PtyChunk_Closed> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_agents, 1, 1);

/**
 * @generated from message graphene.management.v1.PtyInputRequest
 */
export type PtyInputRequest = Message<"graphene.management.v1.PtyInputRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from oneof graphene.management.v1.PtyInputRequest.body
   */
  body: {
    /**
     * Data carries keystrokes, raw.
     *
     * @generated from field: bytes data = 2;
     */
    value: Uint8Array;
    case: "data";
  } | {
    /**
     * @generated from field: graphene.management.v1.PtyInputRequest.Resize resize = 3;
     */
    value: PtyInputRequest_Resize;
    case: "resize";
  } | {
    /**
     * Close buries the shell explicitly.
     *
     * @generated from field: bool close = 4;
     */
    value: boolean;
    case: "close";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message graphene.management.v1.PtyInputRequest.
 * Use `create(PtyInputRequestSchema)` to create a new message.
 */
export const PtyInputRequestSchema: GenMessage<PtyInputRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_agents, 2);

/**
 * @generated from message graphene.management.v1.PtyInputRequest.Resize
 */
export type PtyInputRequest_Resize = Message<"graphene.management.v1.PtyInputRequest.Resize"> & {
  /**
   * @generated from field: uint32 cols = 1;
   */
  cols: number;

  /**
   * @generated from field: uint32 rows = 2;
   */
  rows: number;
};

/**
 * Describes the message graphene.management.v1.PtyInputRequest.Resize.
 * Use `create(PtyInputRequest_ResizeSchema)` to create a new message.
 */
export const PtyInputRequest_ResizeSchema: GenMessage<PtyInputRequest_Resize> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_agents, 2, 0);

/**
 * @generated from message graphene.management.v1.PtyInputResponse
 */
export type PtyInputResponse = Message<"graphene.management.v1.PtyInputResponse"> & {
};

/**
 * Describes the message graphene.management.v1.PtyInputResponse.
 * Use `create(PtyInputResponseSchema)` to create a new message.
 */
export const PtyInputResponseSchema: GenMessage<PtyInputResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_agents, 3);

/**
 * AgentsAPI is the operator's hand on a MACHINE: an interactive shell
 * on the box whose agent is connected, over the door — no ssh keys, no
 * direct reachability, the same token and audit as every other verb.
 *
 * A browser cannot hold a bidirectional stream, so the shell is a
 * half-duplex pair: Pty opens the session and streams its output;
 * PtyInput lands keystrokes, resizes and the explicit close as unary
 * calls addressed by the session id the first chunk announced. The
 * session is mortal by nature: it dies with the stream, the agent's
 * disconnect, or the shell's own exit — nothing reconnects.
 *
 * @generated from service graphene.management.v1.AgentsAPI
 */
export const AgentsAPI: GenService<{
  /**
   * Pty opens a shell on the machine and streams everything it says.
   * The FIRST chunk is always Opened with the session id; the stream
   * ends when the shell dies. Closing the stream closes the shell.
   *
   * @generated from rpc graphene.management.v1.AgentsAPI.Pty
   */
  pty: {
    methodKind: "server_streaming";
    input: typeof PtyRequestSchema;
    output: typeof PtyChunkSchema;
  },
  /**
   * PtyInput writes into a live session: keystrokes, a resize, or the
   * explicit close. One frame per call — input is bursty and small,
   * and unary is what a browser can send.
   *
   * @generated from rpc graphene.management.v1.AgentsAPI.PtyInput
   */
  ptyInput: {
    methodKind: "unary";
    input: typeof PtyInputRequestSchema;
    output: typeof PtyInputResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_management_v1_agents, 0);

