// @generated by protoc-gen-es v2.14.0 with parameter "target=ts"
// @generated from file proto/management/v1/namespaces.proto (package graphene.management.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/management/v1/namespaces.proto.
 */
export const file_proto_management_v1_namespaces: GenFile = /*@__PURE__*/
  fileDesc("CiRwcm90by9tYW5hZ2VtZW50L3YxL25hbWVzcGFjZXMucHJvdG8SFmdyYXBoZW5lLm1hbmFnZW1lbnQudjEiEwoRU2VydmVySW5mb1JlcXVlc3QipgEKElNlcnZlckluZm9SZXNwb25zZRIPCgd2ZXJzaW9uGAEgASgJEkgKCmNvbXBvbmVudHMYAiADKAsyNC5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLlNlcnZlckluZm9SZXNwb25zZS5Db21wb25lbnQaNQoJQ29tcG9uZW50EgwKBG5hbWUYASABKAkSCgoCb2sYAiABKAgSDgoGZGV0YWlsGAMgASgJIg8KDVdob2FtaVJlcXVlc3QiMQoOV2hvYW1pUmVzcG9uc2USDAoEcm9sZRgBIAEoCRIRCgluYW1lc3BhY2UYAiABKAkyzQEKDU5hbWVzcGFjZXNBUEkSVwoGV2hvYW1pEiUuZ3JhcGhlbmUubWFuYWdlbWVudC52MS5XaG9hbWlSZXF1ZXN0GiYuZ3JhcGhlbmUubWFuYWdlbWVudC52MS5XaG9hbWlSZXNwb25zZRJjCgpTZXJ2ZXJJbmZvEikuZ3JhcGhlbmUubWFuYWdlbWVudC52MS5TZXJ2ZXJJbmZvUmVxdWVzdBoqLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuU2VydmVySW5mb1Jlc3BvbnNlQkZaRGdpdGh1Yi5jb20vZ3JhcGhlbmUtY2kvZ3JhcGhlbmUvcGtnL3Byb3RvL21hbmFnZW1lbnQvdjE7bWFuYWdlbWVudHYxYgZwcm90bzM");

/**
 * @generated from message graphene.management.v1.ServerInfoRequest
 */
export type ServerInfoRequest = Message<"graphene.management.v1.ServerInfoRequest"> & {
};

/**
 * Describes the message graphene.management.v1.ServerInfoRequest.
 * Use `create(ServerInfoRequestSchema)` to create a new message.
 */
export const ServerInfoRequestSchema: GenMessage<ServerInfoRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_namespaces, 0);

/**
 * @generated from message graphene.management.v1.ServerInfoResponse
 */
export type ServerInfoResponse = Message<"graphene.management.v1.ServerInfoResponse"> & {
  /**
   * @generated from field: string version = 1;
   */
  version: string;

  /**
   * @generated from field: repeated graphene.management.v1.ServerInfoResponse.Component components = 2;
   */
  components: ServerInfoResponse_Component[];
};

/**
 * Describes the message graphene.management.v1.ServerInfoResponse.
 * Use `create(ServerInfoResponseSchema)` to create a new message.
 */
export const ServerInfoResponseSchema: GenMessage<ServerInfoResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_namespaces, 1);

/**
 * @generated from message graphene.management.v1.ServerInfoResponse.Component
 */
export type ServerInfoResponse_Component = Message<"graphene.management.v1.ServerInfoResponse.Component"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: bool ok = 2;
   */
  ok: boolean;

  /**
   * Detail says what's wrong when ok is false.
   *
   * @generated from field: string detail = 3;
   */
  detail: string;
};

/**
 * Describes the message graphene.management.v1.ServerInfoResponse.Component.
 * Use `create(ServerInfoResponse_ComponentSchema)` to create a new message.
 */
export const ServerInfoResponse_ComponentSchema: GenMessage<ServerInfoResponse_Component> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_namespaces, 1, 0);

/**
 * @generated from message graphene.management.v1.WhoamiRequest
 */
export type WhoamiRequest = Message<"graphene.management.v1.WhoamiRequest"> & {
};

/**
 * Describes the message graphene.management.v1.WhoamiRequest.
 * Use `create(WhoamiRequestSchema)` to create a new message.
 */
export const WhoamiRequestSchema: GenMessage<WhoamiRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_namespaces, 2);

/**
 * @generated from message graphene.management.v1.WhoamiResponse
 */
export type WhoamiResponse = Message<"graphene.management.v1.WhoamiResponse"> & {
  /**
   * Role: admin | run | agent.
   *
   * @generated from field: string role = 1;
   */
  role: string;

  /**
   * Namespace the token is scoped to; "*" — every namespace.
   *
   * @generated from field: string namespace = 2;
   */
  namespace: string;
};

/**
 * Describes the message graphene.management.v1.WhoamiResponse.
 * Use `create(WhoamiResponseSchema)` to create a new message.
 */
export const WhoamiResponseSchema: GenMessage<WhoamiResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_namespaces, 3);

/**
 * NamespacesAPI manages the isolation units of an installation. A
 * graphene namespace is SYMMETRIC to a Temporal namespace: records,
 * queues, visibility, the ownership tree — all isolated by the durable
 * core itself. Tokens are scoped to one namespace; in the cloud a
 * namespace becomes an organization's home.
 * A namespace is DECLARED like everything else: `apply namespace <name>`
 * in the default namespace, listed by `get namespace`. What remains
 * here is what is not a record — who the caller is, and what the
 * installation is.
 *
 * @generated from service graphene.management.v1.NamespacesAPI
 */
export const NamespacesAPI: GenService<{
  /**
   * Whoami answers who the caller's token is: role and namespace scope.
   * Any authenticated principal may ask — this is login's handshake.
   *
   * @generated from rpc graphene.management.v1.NamespacesAPI.Whoami
   */
  whoami: {
    methodKind: "unary";
    input: typeof WhoamiRequestSchema;
    output: typeof WhoamiResponseSchema;
  },
  /**
   * ServerInfo reports the installation: version and component health —
   * the console's status line. Any authenticated principal may ask.
   *
   * @generated from rpc graphene.management.v1.NamespacesAPI.ServerInfo
   */
  serverInfo: {
    methodKind: "unary";
    input: typeof ServerInfoRequestSchema;
    output: typeof ServerInfoResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_management_v1_namespaces, 0);

