// @generated by protoc-gen-es v2.14.0 with parameter "target=ts"
// @generated from file proto/management/v1/namespaces.proto (package graphene.management.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/management/v1/namespaces.proto.
 */
export const file_proto_management_v1_namespaces: GenFile = /*@__PURE__*/
  fileDesc("CiRwcm90by9tYW5hZ2VtZW50L3YxL25hbWVzcGFjZXMucHJvdG8SFmdyYXBoZW5lLm1hbmFnZW1lbnQudjEiEwoRU2VydmVySW5mb1JlcXVlc3QipgEKElNlcnZlckluZm9SZXNwb25zZRIPCgd2ZXJzaW9uGAEgASgJEkgKCmNvbXBvbmVudHMYAiADKAsyNC5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLlNlcnZlckluZm9SZXNwb25zZS5Db21wb25lbnQaNQoJQ29tcG9uZW50EgwKBG5hbWUYASABKAkSCgoCb2sYAiABKAgSDgoGZGV0YWlsGAMgASgJMnQKDU5hbWVzcGFjZXNBUEkSYwoKU2VydmVySW5mbxIpLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuU2VydmVySW5mb1JlcXVlc3QaKi5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLlNlcnZlckluZm9SZXNwb25zZUJGWkRnaXRodWIuY29tL2dyYXBoZW5lLWNpL2dyYXBoZW5lL3BrZy9wcm90by9tYW5hZ2VtZW50L3YxO21hbmFnZW1lbnR2MWIGcHJvdG8z");

/**
 * @generated from message graphene.management.v1.ServerInfoRequest
 */
export type ServerInfoRequest = Message<"graphene.management.v1.ServerInfoRequest"> & {
};

/**
 * Describes the message graphene.management.v1.ServerInfoRequest.
 * Use `create(ServerInfoRequestSchema)` to create a new message.
 */
export const ServerInfoRequestSchema: GenMessage<ServerInfoRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_namespaces, 0);

/**
 * @generated from message graphene.management.v1.ServerInfoResponse
 */
export type ServerInfoResponse = Message<"graphene.management.v1.ServerInfoResponse"> & {
  /**
   * @generated from field: string version = 1;
   */
  version: string;

  /**
   * @generated from field: repeated graphene.management.v1.ServerInfoResponse.Component components = 2;
   */
  components: ServerInfoResponse_Component[];
};

/**
 * Describes the message graphene.management.v1.ServerInfoResponse.
 * Use `create(ServerInfoResponseSchema)` to create a new message.
 */
export const ServerInfoResponseSchema: GenMessage<ServerInfoResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_namespaces, 1);

/**
 * @generated from message graphene.management.v1.ServerInfoResponse.Component
 */
export type ServerInfoResponse_Component = Message<"graphene.management.v1.ServerInfoResponse.Component"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: bool ok = 2;
   */
  ok: boolean;

  /**
   * Detail says what's wrong when ok is false.
   *
   * @generated from field: string detail = 3;
   */
  detail: string;
};

/**
 * Describes the message graphene.management.v1.ServerInfoResponse.Component.
 * Use `create(ServerInfoResponse_ComponentSchema)` to create a new message.
 */
export const ServerInfoResponse_ComponentSchema: GenMessage<ServerInfoResponse_Component> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_namespaces, 1, 0);

/**
 * NamespacesAPI manages the isolation units of an installation. A
 * graphene namespace is SYMMETRIC to a Temporal namespace: records,
 * queues, visibility, the ownership tree — all isolated by the durable
 * core itself. Tokens are scoped to one namespace; in the cloud a
 * namespace becomes an organization's home.
 * A namespace is DECLARED like everything else: `apply namespace <name>`
 * in the default namespace, listed by `get namespace`. What remains
 * here is what is not a record — what the installation is. Who the
 * caller is lives in ONE place: RbacAPI.WhoAmI, the login handshake
 * for every kind of principal.
 *
 * @generated from service graphene.management.v1.NamespacesAPI
 */
export const NamespacesAPI: GenService<{
  /**
   * ServerInfo reports the installation: version and component health —
   * the console's status line. Any authenticated principal may ask.
   *
   * @generated from rpc graphene.management.v1.NamespacesAPI.ServerInfo
   */
  serverInfo: {
    methodKind: "unary";
    input: typeof ServerInfoRequestSchema;
    output: typeof ServerInfoResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_management_v1_namespaces, 0);

