// The five dimensions of any entity — state, events, logs, metrics,
// trace — behind ONE surface. State and events come from the plane of
// truth (Temporal: describes and workflow histories) and are complete
// by construction; logs, metrics, and traces come from the telemetry
// plane (OTel backend behind the collector) and are as complete as
// delivery was. Refs address anything: "run/x", "agent/vm-1",
// "vpc.network/net", "artifact/r".

// @generated by protoc-gen-es v2.14.0 with parameter "target=ts"
// @generated from file proto/management/v1/observe.proto (package graphene.management.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Resource } from "./resources_pb";
import { file_proto_management_v1_resources } from "./resources_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/management/v1/observe.proto.
 */
export const file_proto_management_v1_observe: GenFile = /*@__PURE__*/
  fileDesc("CiFwcm90by9tYW5hZ2VtZW50L3YxL29ic2VydmUucHJvdG8SFmdyYXBoZW5lLm1hbmFnZW1lbnQudjEiIgoTT2JzZXJ2ZVN0YXRlUmVxdWVzdBILCgNyZWYYASABKAkiWgoUT2JzZXJ2ZVN0YXRlUmVzcG9uc2USDgoGc3RhdHVzGAEgASgJEjIKCHJlc291cmNlGAIgASgLMiAuZ3JhcGhlbmUubWFuYWdlbWVudC52MS5SZXNvdXJjZSJZCg1FdmVudHNSZXF1ZXN0EgsKA3JlZhgBIAEoCRIWCg5hZnRlcl9ldmVudF9pZBgCIAEoAxIOCgZmb2xsb3cYAyABKAgSEwoLYWN0aXZpdHlfaWQYBCABKAkiuwEKBUV2ZW50EhAKCGV2ZW50X2lkGAEgASgDEhYKDnRpbWVfdW5peF9uYW5vGAIgASgDEgwKBGtpbmQYAyABKAkSDwoHc3ViamVjdBgEIAEoCRINCgVhZ2VudBgFIAEoCRIOCgZzdGF0dXMYBiABKAkSDQoFZXJyb3IYByABKAkSDwoHYXR0ZW1wdBgIIAEoBRINCgVpbnB1dBgJIAEoDBIOCgZyZXN1bHQYCiABKAwSCwoDcmF3GAsgASgMIkMKC0xvZ3NSZXF1ZXN0EgsKA3JlZhgBIAEoCRIOCgZmb2xsb3cYAiABKAgSFwoPc2luY2VfdW5peF9uYW5vGAMgASgDIr0BCglMb2dSZWNvcmQSFgoOdGltZV91bml4X25hbm8YASABKAMSEAoIc2V2ZXJpdHkYAiABKAkSDAoEYm9keRgDIAEoCRJFCgphdHRyaWJ1dGVzGAQgAygLMjEuZ3JhcGhlbmUubWFuYWdlbWVudC52MS5Mb2dSZWNvcmQuQXR0cmlidXRlc0VudHJ5GjEKD0F0dHJpYnV0ZXNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIk0KDk1ldHJpY3NSZXF1ZXN0EgsKA3JlZhgBIAEoCRIXCg9zdGFydF91bml4X25hbm8YAiABKAMSFQoNZW5kX3VuaXhfbmFubxgDIAEoAyIhCg9NZXRyaWNzUmVzcG9uc2USDgoGc2VyaWVzGAEgASgMIhsKDFRyYWNlUmVxdWVzdBILCgNyZWYYASABKAkiHgoNVHJhY2VSZXNwb25zZRINCgV0cmFjZRgBIAEoDDLGAwoKT2JzZXJ2ZUFQSRJiCgVTdGF0ZRIrLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuT2JzZXJ2ZVN0YXRlUmVxdWVzdBosLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuT2JzZXJ2ZVN0YXRlUmVzcG9uc2USUAoGRXZlbnRzEiUuZ3JhcGhlbmUubWFuYWdlbWVudC52MS5FdmVudHNSZXF1ZXN0Gh0uZ3JhcGhlbmUubWFuYWdlbWVudC52MS5FdmVudDABElAKBExvZ3MSIy5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLkxvZ3NSZXF1ZXN0GiEuZ3JhcGhlbmUubWFuYWdlbWVudC52MS5Mb2dSZWNvcmQwARJaCgdNZXRyaWNzEiYuZ3JhcGhlbmUubWFuYWdlbWVudC52MS5NZXRyaWNzUmVxdWVzdBonLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuTWV0cmljc1Jlc3BvbnNlElQKBVRyYWNlEiQuZ3JhcGhlbmUubWFuYWdlbWVudC52MS5UcmFjZVJlcXVlc3QaJS5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLlRyYWNlUmVzcG9uc2VCRlpEZ2l0aHViLmNvbS9ncmFwaGVuZS1jaS9ncmFwaGVuZS9wa2cvcHJvdG8vbWFuYWdlbWVudC92MTttYW5hZ2VtZW50djFiBnByb3RvMw", [file_proto_management_v1_resources]);

/**
 * @generated from message graphene.management.v1.ObserveStateRequest
 */
export type ObserveStateRequest = Message<"graphene.management.v1.ObserveStateRequest"> & {
  /**
   * @generated from field: string ref = 1;
   */
  ref: string;
};

/**
 * Describes the message graphene.management.v1.ObserveStateRequest.
 * Use `create(ObserveStateRequestSchema)` to create a new message.
 */
export const ObserveStateRequestSchema: GenMessage<ObserveStateRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_observe, 0);

/**
 * @generated from message graphene.management.v1.ObserveStateResponse
 */
export type ObserveStateResponse = Message<"graphene.management.v1.ObserveStateResponse"> & {
  /**
   * Status is the workflow execution status (runs and entities alike).
   *
   * @generated from field: string status = 1;
   */
  status: string;

  /**
   * Resource is the full record for entity refs (describe); unset for
   * plain runs.
   *
   * @generated from field: graphene.management.v1.Resource resource = 2;
   */
  resource?: Resource | undefined;
};

/**
 * Describes the message graphene.management.v1.ObserveStateResponse.
 * Use `create(ObserveStateResponseSchema)` to create a new message.
 */
export const ObserveStateResponseSchema: GenMessage<ObserveStateResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_observe, 1);

/**
 * @generated from message graphene.management.v1.EventsRequest
 */
export type EventsRequest = Message<"graphene.management.v1.EventsRequest"> & {
  /**
   * @generated from field: string ref = 1;
   */
  ref: string;

  /**
   * Resume: emit only events after this history event id.
   *
   * @generated from field: int64 after_event_id = 2;
   */
  afterEventId: bigint;

  /**
   * Follow keeps the stream open for new events until the workflow
   * closes (or forever, for a living entity).
   *
   * @generated from field: bool follow = 3;
   */
  follow: boolean;

  /**
   * ActivityId slices the stream to one activity execution.
   *
   * @generated from field: string activity_id = 4;
   */
  activityId: string;
};

/**
 * Describes the message graphene.management.v1.EventsRequest.
 * Use `create(EventsRequestSchema)` to create a new message.
 */
export const EventsRequestSchema: GenMessage<EventsRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_observe, 2);

/**
 * @generated from message graphene.management.v1.Event
 */
export type Event = Message<"graphene.management.v1.Event"> & {
  /**
   * EventId is the stable cursor: the Temporal history event id.
   *
   * @generated from field: int64 event_id = 1;
   */
  eventId: bigint;

  /**
   * @generated from field: int64 time_unix_nano = 2;
   */
  timeUnixNano: bigint;

  /**
   * Kind classifies for rendering: run-started, activity-scheduled,
   * activity-completed, activity-failed, command-received,
   * internal-<type>, ... Nothing is omitted — unclassified history
   * events pass through as internal-*.
   *
   * @generated from field: string kind = 3;
   */
  kind: string;

  /**
   * Subject: the activity/command name the event is about.
   *
   * @generated from field: string subject = 4;
   */
  subject: string;

  /**
   * Agent executing it, when the task queue names one.
   *
   * @generated from field: string agent = 5;
   */
  agent: string;

  /**
   * @generated from field: string status = 6;
   */
  status: string;

  /**
   * @generated from field: string error = 7;
   */
  error: string;

  /**
   * @generated from field: int32 attempt = 8;
   */
  attempt: number;

  /**
   * Input/result payloads as JSON — history is secret-free by
   * construction (secrets travel as names), so nothing is stripped.
   *
   * @generated from field: bytes input = 9;
   */
  input: Uint8Array;

  /**
   * @generated from field: bytes result = 10;
   */
  result: Uint8Array;

  /**
   * Raw is the entire history event (protojson) for drill-down.
   *
   * @generated from field: bytes raw = 11;
   */
  raw: Uint8Array;
};

/**
 * Describes the message graphene.management.v1.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_observe, 3);

/**
 * @generated from message graphene.management.v1.LogsRequest
 */
export type LogsRequest = Message<"graphene.management.v1.LogsRequest"> & {
  /**
   * @generated from field: string ref = 1;
   */
  ref: string;

  /**
   * @generated from field: bool follow = 2;
   */
  follow: boolean;

  /**
   * @generated from field: int64 since_unix_nano = 3;
   */
  sinceUnixNano: bigint;
};

/**
 * Describes the message graphene.management.v1.LogsRequest.
 * Use `create(LogsRequestSchema)` to create a new message.
 */
export const LogsRequestSchema: GenMessage<LogsRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_observe, 4);

/**
 * @generated from message graphene.management.v1.LogRecord
 */
export type LogRecord = Message<"graphene.management.v1.LogRecord"> & {
  /**
   * @generated from field: int64 time_unix_nano = 1;
   */
  timeUnixNano: bigint;

  /**
   * @generated from field: string severity = 2;
   */
  severity: string;

  /**
   * @generated from field: string body = 3;
   */
  body: string;

  /**
   * @generated from field: map<string, string> attributes = 4;
   */
  attributes: { [key: string]: string };
};

/**
 * Describes the message graphene.management.v1.LogRecord.
 * Use `create(LogRecordSchema)` to create a new message.
 */
export const LogRecordSchema: GenMessage<LogRecord> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_observe, 5);

/**
 * @generated from message graphene.management.v1.MetricsRequest
 */
export type MetricsRequest = Message<"graphene.management.v1.MetricsRequest"> & {
  /**
   * @generated from field: string ref = 1;
   */
  ref: string;

  /**
   * @generated from field: int64 start_unix_nano = 2;
   */
  startUnixNano: bigint;

  /**
   * @generated from field: int64 end_unix_nano = 3;
   */
  endUnixNano: bigint;
};

/**
 * Describes the message graphene.management.v1.MetricsRequest.
 * Use `create(MetricsRequestSchema)` to create a new message.
 */
export const MetricsRequestSchema: GenMessage<MetricsRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_observe, 6);

/**
 * @generated from message graphene.management.v1.MetricsResponse
 */
export type MetricsResponse = Message<"graphene.management.v1.MetricsResponse"> & {
  /**
   * Series is backend-shaped JSON; the contract firms up with the
   * chosen backend.
   *
   * @generated from field: bytes series = 1;
   */
  series: Uint8Array;
};

/**
 * Describes the message graphene.management.v1.MetricsResponse.
 * Use `create(MetricsResponseSchema)` to create a new message.
 */
export const MetricsResponseSchema: GenMessage<MetricsResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_observe, 7);

/**
 * @generated from message graphene.management.v1.TraceRequest
 */
export type TraceRequest = Message<"graphene.management.v1.TraceRequest"> & {
  /**
   * @generated from field: string ref = 1;
   */
  ref: string;
};

/**
 * Describes the message graphene.management.v1.TraceRequest.
 * Use `create(TraceRequestSchema)` to create a new message.
 */
export const TraceRequestSchema: GenMessage<TraceRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_observe, 8);

/**
 * @generated from message graphene.management.v1.TraceResponse
 */
export type TraceResponse = Message<"graphene.management.v1.TraceResponse"> & {
  /**
   * Trace is the span tree as JSON.
   *
   * @generated from field: bytes trace = 1;
   */
  trace: Uint8Array;
};

/**
 * Describes the message graphene.management.v1.TraceResponse.
 * Use `create(TraceResponseSchema)` to create a new message.
 */
export const TraceResponseSchema: GenMessage<TraceResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_observe, 9);

/**
 * @generated from service graphene.management.v1.ObserveAPI
 */
export const ObserveAPI: GenService<{
  /**
   * State is dimension 1: the full current record.
   *
   * @generated from rpc graphene.management.v1.ObserveAPI.State
   */
  state: {
    methodKind: "unary";
    input: typeof ObserveStateRequestSchema;
    output: typeof ObserveStateResponseSchema;
  },
  /**
   * Events is dimension 2: the entity's own history, translated —
   * classification without omission (raw carries everything).
   *
   * @generated from rpc graphene.management.v1.ObserveAPI.Events
   */
  events: {
    methodKind: "server_streaming";
    input: typeof EventsRequestSchema;
    output: typeof EventSchema;
  },
  /**
   * Logs is dimension 3 (telemetry plane).
   *
   * @generated from rpc graphene.management.v1.ObserveAPI.Logs
   */
  logs: {
    methodKind: "server_streaming";
    input: typeof LogsRequestSchema;
    output: typeof LogRecordSchema;
  },
  /**
   * Metrics is dimension 4 (telemetry plane).
   *
   * @generated from rpc graphene.management.v1.ObserveAPI.Metrics
   */
  metrics: {
    methodKind: "unary";
    input: typeof MetricsRequestSchema;
    output: typeof MetricsResponseSchema;
  },
  /**
   * Trace is dimension 5 (telemetry plane).
   *
   * @generated from rpc graphene.management.v1.ObserveAPI.Trace
   */
  trace: {
    methodKind: "unary";
    input: typeof TraceRequestSchema;
    output: typeof TraceResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_management_v1_observe, 0);

