// @generated by protoc-gen-es v2.14.0 with parameter "target=ts"
// @generated from file proto/management/v1/rbac.proto (package graphene.management.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/management/v1/rbac.proto.
 */
export const file_proto_management_v1_rbac: GenFile = /*@__PURE__*/
  fileDesc("Ch5wcm90by9tYW5hZ2VtZW50L3YxL3JiYWMucHJvdG8SFmdyYXBoZW5lLm1hbmFnZW1lbnQudjEiRgoSSXNzdWVUb2tlblJlc3BvbnNlEhAKCHRva2VuX2lkGAEgASgJEg0KBXRva2VuGAIgASgJEg8KB2V4cGlyZXMYAyABKAkiSgoRSXNzdWVUb2tlblJlcXVlc3QSDwoHYWNjb3VudBgBIAEoCRITCgt0dGxfc2Vjb25kcxgCIAEoAxIPCgdjb21tZW50GAMgASgJIg8KDVdob0FtSVJlcXVlc3QiegoOV2hvQW1JUmVzcG9uc2USDwoHc3ViamVjdBgBIAEoCRIOCgZncm91cHMYAiADKAkSEQoJbmFtZXNwYWNlGAMgASgJEg0KBXJvbGVzGAQgAygJEg8KB2FsbG93ZWQYBSADKAkSFAoMY2x1c3Rlcl93aWRlGAYgASgIMscBCgdSYmFjQVBJEmMKCklzc3VlVG9rZW4SKS5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLklzc3VlVG9rZW5SZXF1ZXN0GiouZ3JhcGhlbmUubWFuYWdlbWVudC52MS5Jc3N1ZVRva2VuUmVzcG9uc2USVwoGV2hvQW1JEiUuZ3JhcGhlbmUubWFuYWdlbWVudC52MS5XaG9BbUlSZXF1ZXN0GiYuZ3JhcGhlbmUubWFuYWdlbWVudC52MS5XaG9BbUlSZXNwb25zZUJGWkRnaXRodWIuY29tL2dyYXBoZW5lLWNpL2dyYXBoZW5lL3BrZy9wcm90by9tYW5hZ2VtZW50L3YxO21hbmFnZW1lbnR2MWIGcHJvdG8z");

/**
 * @generated from message graphene.management.v1.IssueTokenResponse
 */
export type IssueTokenResponse = Message<"graphene.management.v1.IssueTokenResponse"> & {
  /**
   * @generated from field: string token_id = 1;
   */
  tokenId: string;

  /**
   * Token is the VALUE, returned once and never stored.
   *
   * @generated from field: string token = 2;
   */
  token: string;

  /**
   * @generated from field: string expires = 3;
   */
  expires: string;
};

/**
 * Describes the message graphene.management.v1.IssueTokenResponse.
 * Use `create(IssueTokenResponseSchema)` to create a new message.
 */
export const IssueTokenResponseSchema: GenMessage<IssueTokenResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_rbac, 0);

/**
 * @generated from message graphene.management.v1.IssueTokenRequest
 */
export type IssueTokenRequest = Message<"graphene.management.v1.IssueTokenRequest"> & {
  /**
   * @generated from field: string account = 1;
   */
  account: string;

  /**
   * TtlSeconds bounds the token's life; 0 means until it is revoked.
   *
   * @generated from field: int64 ttl_seconds = 2;
   */
  ttlSeconds: bigint;

  /**
   * @generated from field: string comment = 3;
   */
  comment: string;
};

/**
 * Describes the message graphene.management.v1.IssueTokenRequest.
 * Use `create(IssueTokenRequestSchema)` to create a new message.
 */
export const IssueTokenRequestSchema: GenMessage<IssueTokenRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_rbac, 1);

/**
 * @generated from message graphene.management.v1.WhoAmIRequest
 */
export type WhoAmIRequest = Message<"graphene.management.v1.WhoAmIRequest"> & {
};

/**
 * Describes the message graphene.management.v1.WhoAmIRequest.
 * Use `create(WhoAmIRequestSchema)` to create a new message.
 */
export const WhoAmIRequestSchema: GenMessage<WhoAmIRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_rbac, 2);

/**
 * @generated from message graphene.management.v1.WhoAmIResponse
 */
export type WhoAmIResponse = Message<"graphene.management.v1.WhoAmIResponse"> & {
  /**
   * @generated from field: string subject = 1;
   */
  subject: string;

  /**
   * @generated from field: repeated string groups = 2;
   */
  groups: string[];

  /**
   * @generated from field: string namespace = 3;
   */
  namespace: string;

  /**
   * Roles are the role names bound to this caller here.
   *
   * @generated from field: repeated string roles = 4;
   */
  roles: string[];

  /**
   * Allowed lists "verb kind" pairs this caller may do — enough for a
   * UI to hide what it must not offer.
   *
   * @generated from field: repeated string allowed = 5;
   */
  allowed: string[];

  /**
   * ClusterWide says this caller's rights span every namespace — the
   * signal a client needs to offer namespace switching (the
   * x-graphene-namespace header on any call).
   *
   * @generated from field: bool cluster_wide = 6;
   */
  clusterWide: boolean;
};

/**
 * Describes the message graphene.management.v1.WhoAmIResponse.
 * Use `create(WhoAmIResponseSchema)` to create a new message.
 */
export const WhoAmIResponseSchema: GenMessage<WhoAmIResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_rbac, 3);

/**
 * RbacAPI administers who may do what: roles, their bindings, and the
 * service accounts of this installation. People come from the identity
 * provider and are never stored here; machines are accounts, and their
 * tokens are issued here and kept by hash only.
 * Roles, bindings and accounts are RECORDS: they are declared with
 * Apply, changed with Invoke and read with Get — no door of their own.
 * Two calls remain here, and only because they cannot be commands:
 *
 * @generated from service graphene.management.v1.RbacAPI
 */
export const RbacAPI: GenService<{
  /**
   * IssueToken mints a token for a service account. It cannot be a
   * command: a command's payload AND its result both land in the
   * record's history, and a token value must land nowhere. The value
   * is returned exactly once, here; the record keeps only its hash.
   *
   * @generated from rpc graphene.management.v1.RbacAPI.IssueToken
   */
  issueToken: {
    methodKind: "unary";
    input: typeof IssueTokenRequestSchema;
    output: typeof IssueTokenResponseSchema;
  },
  /**
   * WhoAmI answers who the caller is and what they may do — a property
   * of the caller, not of any record.
   *
   * @generated from rpc graphene.management.v1.RbacAPI.WhoAmI
   */
  whoAmI: {
    methodKind: "unary";
    input: typeof WhoAmIRequestSchema;
    output: typeof WhoAmIResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_management_v1_rbac, 0);

