// @generated by protoc-gen-es v2.14.0 with parameter "target=ts"
// @generated from file proto/management/v1/revisions.proto (package graphene.management.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/management/v1/revisions.proto.
 */
export const file_proto_management_v1_revisions: GenFile = /*@__PURE__*/
  fileDesc("CiNwcm90by9tYW5hZ2VtZW50L3YxL3JldmlzaW9ucy5wcm90bxIWZ3JhcGhlbmUubWFuYWdlbWVudC52MSJNChJNYXRlcmlhbGl6ZVJlcXVlc3QSEwoLcGlwZWxpbmVfaWQYASABKAkSDgoGc291cmNlGAIgASgMEhIKCnNvdXJjZV9yZWYYAyABKAkibQoQTWF0ZXJpYWxpemVFdmVudBINCgVzdGFnZRgBIAEoCRIPCgdtZXNzYWdlGAIgASgJEjkKBnJlc3VsdBgDIAEoCzIpLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuTWF0ZXJpYWxpemVSZXN1bHQiSQoRTWF0ZXJpYWxpemVSZXN1bHQSEwoLcmV2aXNpb25faWQYASABKAkSDQoFaW1hZ2UYAiABKAkSEAoIbWFuaWZlc3QYAyABKAwi1QEKElJ1blJldmlzaW9uUmVxdWVzdBITCgtwaXBlbGluZV9pZBgBIAEoCRITCgtyZXZpc2lvbl9pZBgCIAEoCRIOCgZydW5faWQYAyABKAkSDgoGcGFyYW1zGAQgASgMEkYKBmxhYmVscxgFIAMoCzI2LmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuUnVuUmV2aXNpb25SZXF1ZXN0LkxhYmVsc0VudHJ5Gi0KC0xhYmVsc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEiQwoTUnVuUmV2aXNpb25SZXNwb25zZRITCgt3b3JrZmxvd19pZBgBIAEoCRIXCg90ZW1wb3JhbF9ydW5faWQYAiABKAky3QEKDFJldmlzaW9uc0FQSRJlCgtNYXRlcmlhbGl6ZRIqLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuTWF0ZXJpYWxpemVSZXF1ZXN0GiguZ3JhcGhlbmUubWFuYWdlbWVudC52MS5NYXRlcmlhbGl6ZUV2ZW50MAESZgoLUnVuUmV2aXNpb24SKi5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLlJ1blJldmlzaW9uUmVxdWVzdBorLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuUnVuUmV2aXNpb25SZXNwb25zZUJGWkRnaXRodWIuY29tL2dyYXBoZW5lLWNpL2dyYXBoZW5lL3BrZy9wcm90by9tYW5hZ2VtZW50L3YxO21hbmFnZW1lbnR2MWIGcHJvdG8z");

/**
 * @generated from message graphene.management.v1.MaterializeRequest
 */
export type MaterializeRequest = Message<"graphene.management.v1.MaterializeRequest"> & {
  /**
   * @generated from field: string pipeline_id = 1;
   */
  pipelineId: string;

  /**
   * The full source tree as tar.gz — the tree root is the build root:
   * `go build .`, one package main. Empty builds a SOURCE record of
   * the pipeline, whose tree already lives on the server.
   *
   * @generated from field: bytes source = 2;
   */
  source: Uint8Array;

  /**
   * Source names which source to build ("gitsource/main"); empty takes
   * the pipeline's only one.
   *
   * @generated from field: string source_ref = 3;
   */
  sourceRef: string;
};

/**
 * Describes the message graphene.management.v1.MaterializeRequest.
 * Use `create(MaterializeRequestSchema)` to create a new message.
 */
export const MaterializeRequestSchema: GenMessage<MaterializeRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_revisions, 0);

/**
 * @generated from message graphene.management.v1.MaterializeEvent
 */
export type MaterializeEvent = Message<"graphene.management.v1.MaterializeEvent"> & {
  /**
   * Stage: "upload" | "runtime" | "build" | "describe" | "publish" |
   * "done" — the phase this event reports.
   *
   * @generated from field: string stage = 1;
   */
  stage: string;

  /**
   * Message is one progress line (a build log line, a status).
   *
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * Result is set on the final "done" event.
   *
   * @generated from field: graphene.management.v1.MaterializeResult result = 3;
   */
  result?: MaterializeResult | undefined;
};

/**
 * Describes the message graphene.management.v1.MaterializeEvent.
 * Use `create(MaterializeEventSchema)` to create a new message.
 */
export const MaterializeEventSchema: GenMessage<MaterializeEvent> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_revisions, 1);

/**
 * @generated from message graphene.management.v1.MaterializeResult
 */
export type MaterializeResult = Message<"graphene.management.v1.MaterializeResult"> & {
  /**
   * @generated from field: string revision_id = 1;
   */
  revisionId: string;

  /**
   * @generated from field: string image = 2;
   */
  image: string;

  /**
   * The revision's manifest as protojson — what Plan renders.
   *
   * @generated from field: bytes manifest = 3;
   */
  manifest: Uint8Array;
};

/**
 * Describes the message graphene.management.v1.MaterializeResult.
 * Use `create(MaterializeResultSchema)` to create a new message.
 */
export const MaterializeResultSchema: GenMessage<MaterializeResult> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_revisions, 2);

/**
 * @generated from message graphene.management.v1.RunRevisionRequest
 */
export type RunRevisionRequest = Message<"graphene.management.v1.RunRevisionRequest"> & {
  /**
   * @generated from field: string pipeline_id = 1;
   */
  pipelineId: string;

  /**
   * @generated from field: string revision_id = 2;
   */
  revisionId: string;

  /**
   * @generated from field: string run_id = 3;
   */
  runId: string;

  /**
   * @generated from field: bytes params = 4;
   */
  params: Uint8Array;

  /**
   * @generated from field: map<string, string> labels = 5;
   */
  labels: { [key: string]: string };
};

/**
 * Describes the message graphene.management.v1.RunRevisionRequest.
 * Use `create(RunRevisionRequestSchema)` to create a new message.
 */
export const RunRevisionRequestSchema: GenMessage<RunRevisionRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_revisions, 3);

/**
 * @generated from message graphene.management.v1.RunRevisionResponse
 */
export type RunRevisionResponse = Message<"graphene.management.v1.RunRevisionResponse"> & {
  /**
   * @generated from field: string workflow_id = 1;
   */
  workflowId: string;

  /**
   * @generated from field: string temporal_run_id = 2;
   */
  temporalRunId: string;
};

/**
 * Describes the message graphene.management.v1.RunRevisionResponse.
 * Use `create(RunRevisionResponseSchema)` to create a new message.
 */
export const RunRevisionResponseSchema: GenMessage<RunRevisionResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_revisions, 4);

/**
 * RevisionsAPI is the source-first contour: a SOURCE TREE goes in, the
 * server materializes it (build in a runtime container, manifest from
 * the binary's describe mode, ko-style OCI push), and the result is a
 * PIPELINE REVISION — runnable as a draft, activatable as the version
 * automatic starts use. No user-side push exists on this path.
 *
 * @generated from service graphene.management.v1.RevisionsAPI
 */
export const RevisionsAPI: GenService<{
  /**
   * Materialize STREAMS progress: a source build takes minutes, and a
   * silent request dies on the first idle NAT between the client and
   * the door. The stream is also the Studio build log.
   *
   * @generated from rpc graphene.management.v1.RevisionsAPI.Materialize
   */
  materialize: {
    methodKind: "server_streaming";
    input: typeof MaterializeRequestSchema;
    output: typeof MaterializeEventSchema;
  },
  /**
   * @generated from rpc graphene.management.v1.RevisionsAPI.RunRevision
   */
  runRevision: {
    methodKind: "unary";
    input: typeof RunRevisionRequestSchema;
    output: typeof RunRevisionResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_management_v1_revisions, 0);

