// @generated by protoc-gen-es v2.14.0 with parameter "target=ts"
// @generated from file proto/management/v1/runs.proto (package graphene.management.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/management/v1/runs.proto.
 */
export const file_proto_management_v1_runs: GenFile = /*@__PURE__*/
  fileDesc("Ch5wcm90by9tYW5hZ2VtZW50L3YxL3J1bnMucHJvdG8SFmdyYXBoZW5lLm1hbmFnZW1lbnQudjEixgEKD1N0YXJ0UnVuUmVxdWVzdBIOCgZydW5faWQYASABKAkSEAoIcGlwZWxpbmUYAiABKAkSDgoGcGFyYW1zGAMgASgMEg0KBWltYWdlGAQgASgJEkMKBmxhYmVscxgFIAMoCzIzLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuU3RhcnRSdW5SZXF1ZXN0LkxhYmVsc0VudHJ5Gi0KC0xhYmVsc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEiQAoQU3RhcnRSdW5SZXNwb25zZRITCgt3b3JrZmxvd19pZBgBIAEoCRIXCg90ZW1wb3JhbF9ydW5faWQYAiABKAkiHwoNR2V0UnVuUmVxdWVzdBIOCgZydW5faWQYASABKAkiIAoOR2V0UnVuUmVzcG9uc2USDgoGc3RhdHVzGAEgASgJIiEKD1dhdGNoUnVuUmVxdWVzdBIOCgZydW5faWQYASABKAkiHwoNV2F0Y2hSdW5FdmVudBIOCgZzdGF0dXMYASABKAkiIgoQUnVuUmVzdWx0UmVxdWVzdBIOCgZydW5faWQYASABKAkiIwoRUnVuUmVzdWx0UmVzcG9uc2USDgoGcmVzdWx0GAEgASgMIiIKEENhbmNlbFJ1blJlcXVlc3QSDgoGcnVuX2lkGAEgASgJIhMKEUNhbmNlbFJ1blJlc3BvbnNlMuMDCgdSdW5zQVBJEl0KCFN0YXJ0UnVuEicuZ3JhcGhlbmUubWFuYWdlbWVudC52MS5TdGFydFJ1blJlcXVlc3QaKC5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLlN0YXJ0UnVuUmVzcG9uc2USVwoGR2V0UnVuEiUuZ3JhcGhlbmUubWFuYWdlbWVudC52MS5HZXRSdW5SZXF1ZXN0GiYuZ3JhcGhlbmUubWFuYWdlbWVudC52MS5HZXRSdW5SZXNwb25zZRJcCghXYXRjaFJ1bhInLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuV2F0Y2hSdW5SZXF1ZXN0GiUuZ3JhcGhlbmUubWFuYWdlbWVudC52MS5XYXRjaFJ1bkV2ZW50MAESYAoJUnVuUmVzdWx0EiguZ3JhcGhlbmUubWFuYWdlbWVudC52MS5SdW5SZXN1bHRSZXF1ZXN0GikuZ3JhcGhlbmUubWFuYWdlbWVudC52MS5SdW5SZXN1bHRSZXNwb25zZRJgCglDYW5jZWxSdW4SKC5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLkNhbmNlbFJ1blJlcXVlc3QaKS5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLkNhbmNlbFJ1blJlc3BvbnNlQkZaRGdpdGh1Yi5jb20vZ3JhcGhlbmUtY2kvZ3JhcGhlbmUvcGtnL3Byb3RvL21hbmFnZW1lbnQvdjE7bWFuYWdlbWVudHYxYgZwcm90bzM");

/**
 * @generated from message graphene.management.v1.StartRunRequest
 */
export type StartRunRequest = Message<"graphene.management.v1.StartRunRequest"> & {
  /**
   * @generated from field: string run_id = 1;
   */
  runId: string;

  /**
   * Pipeline is the workflow type on the wire — the pipeline id.
   *
   * @generated from field: string pipeline = 2;
   */
  pipeline: string;

  /**
   * Params is the typed params value of the pipeline, as JSON.
   *
   * @generated from field: bytes params = 3;
   */
  params: Uint8Array;

  /**
   * Image, when set, makes the run MANAGED: the server launches the
   * worker container itself.
   *
   * @generated from field: string image = 4;
   */
  image: string;

  /**
   * Labels mark the run for later selection — same semantics as
   * resource labels; "graphene.io/" keys are reserved for the system.
   *
   * @generated from field: map<string, string> labels = 5;
   */
  labels: { [key: string]: string };
};

/**
 * Describes the message graphene.management.v1.StartRunRequest.
 * Use `create(StartRunRequestSchema)` to create a new message.
 */
export const StartRunRequestSchema: GenMessage<StartRunRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_runs, 0);

/**
 * @generated from message graphene.management.v1.StartRunResponse
 */
export type StartRunResponse = Message<"graphene.management.v1.StartRunResponse"> & {
  /**
   * @generated from field: string workflow_id = 1;
   */
  workflowId: string;

  /**
   * @generated from field: string temporal_run_id = 2;
   */
  temporalRunId: string;
};

/**
 * Describes the message graphene.management.v1.StartRunResponse.
 * Use `create(StartRunResponseSchema)` to create a new message.
 */
export const StartRunResponseSchema: GenMessage<StartRunResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_runs, 1);

/**
 * @generated from message graphene.management.v1.GetRunRequest
 */
export type GetRunRequest = Message<"graphene.management.v1.GetRunRequest"> & {
  /**
   * @generated from field: string run_id = 1;
   */
  runId: string;
};

/**
 * Describes the message graphene.management.v1.GetRunRequest.
 * Use `create(GetRunRequestSchema)` to create a new message.
 */
export const GetRunRequestSchema: GenMessage<GetRunRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_runs, 2);

/**
 * @generated from message graphene.management.v1.GetRunResponse
 */
export type GetRunResponse = Message<"graphene.management.v1.GetRunResponse"> & {
  /**
   * @generated from field: string status = 1;
   */
  status: string;
};

/**
 * Describes the message graphene.management.v1.GetRunResponse.
 * Use `create(GetRunResponseSchema)` to create a new message.
 */
export const GetRunResponseSchema: GenMessage<GetRunResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_runs, 3);

/**
 * @generated from message graphene.management.v1.WatchRunRequest
 */
export type WatchRunRequest = Message<"graphene.management.v1.WatchRunRequest"> & {
  /**
   * @generated from field: string run_id = 1;
   */
  runId: string;
};

/**
 * Describes the message graphene.management.v1.WatchRunRequest.
 * Use `create(WatchRunRequestSchema)` to create a new message.
 */
export const WatchRunRequestSchema: GenMessage<WatchRunRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_runs, 4);

/**
 * @generated from message graphene.management.v1.WatchRunEvent
 */
export type WatchRunEvent = Message<"graphene.management.v1.WatchRunEvent"> & {
  /**
   * @generated from field: string status = 1;
   */
  status: string;
};

/**
 * Describes the message graphene.management.v1.WatchRunEvent.
 * Use `create(WatchRunEventSchema)` to create a new message.
 */
export const WatchRunEventSchema: GenMessage<WatchRunEvent> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_runs, 5);

/**
 * @generated from message graphene.management.v1.RunResultRequest
 */
export type RunResultRequest = Message<"graphene.management.v1.RunResultRequest"> & {
  /**
   * @generated from field: string run_id = 1;
   */
  runId: string;
};

/**
 * Describes the message graphene.management.v1.RunResultRequest.
 * Use `create(RunResultRequestSchema)` to create a new message.
 */
export const RunResultRequestSchema: GenMessage<RunResultRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_runs, 6);

/**
 * @generated from message graphene.management.v1.RunResultResponse
 */
export type RunResultResponse = Message<"graphene.management.v1.RunResultResponse"> & {
  /**
   * Result is the run's typed Result as JSON.
   *
   * @generated from field: bytes result = 1;
   */
  result: Uint8Array;
};

/**
 * Describes the message graphene.management.v1.RunResultResponse.
 * Use `create(RunResultResponseSchema)` to create a new message.
 */
export const RunResultResponseSchema: GenMessage<RunResultResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_runs, 7);

/**
 * @generated from message graphene.management.v1.CancelRunRequest
 */
export type CancelRunRequest = Message<"graphene.management.v1.CancelRunRequest"> & {
  /**
   * @generated from field: string run_id = 1;
   */
  runId: string;
};

/**
 * Describes the message graphene.management.v1.CancelRunRequest.
 * Use `create(CancelRunRequestSchema)` to create a new message.
 */
export const CancelRunRequestSchema: GenMessage<CancelRunRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_runs, 8);

/**
 * @generated from message graphene.management.v1.CancelRunResponse
 */
export type CancelRunResponse = Message<"graphene.management.v1.CancelRunResponse"> & {
};

/**
 * Describes the message graphene.management.v1.CancelRunResponse.
 * Use `create(CancelRunResponseSchema)` to create a new message.
 */
export const CancelRunResponseSchema: GenMessage<CancelRunResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_runs, 9);

/**
 * RunsAPI starts and observes pipeline runs. The worker — a managed
 * container or an inplace binary — serves the run's queue; the server
 * starts the workflow (and the container, when the run is managed).
 *
 * @generated from service graphene.management.v1.RunsAPI
 */
export const RunsAPI: GenService<{
  /**
   * @generated from rpc graphene.management.v1.RunsAPI.StartRun
   */
  startRun: {
    methodKind: "unary";
    input: typeof StartRunRequestSchema;
    output: typeof StartRunResponseSchema;
  },
  /**
   * @generated from rpc graphene.management.v1.RunsAPI.GetRun
   */
  getRun: {
    methodKind: "unary";
    input: typeof GetRunRequestSchema;
    output: typeof GetRunResponseSchema;
  },
  /**
   * WatchRun streams the run's status transitions until a terminal
   * one; the first message carries the current status immediately.
   *
   * @generated from rpc graphene.management.v1.RunsAPI.WatchRun
   */
  watchRun: {
    methodKind: "server_streaming";
    input: typeof WatchRunRequestSchema;
    output: typeof WatchRunEventSchema;
  },
  /**
   * Result waits for the run to finish and returns its typed result as
   * JSON.
   *
   * @generated from rpc graphene.management.v1.RunsAPI.RunResult
   */
  runResult: {
    methodKind: "unary";
    input: typeof RunResultRequestSchema;
    output: typeof RunResultResponseSchema;
  },
  /**
   * Cancel asks the run to stop; the guaranteed-teardown path still
   * runs (unlike a terminate).
   * Listing lives in ResourcesAPI.List under the system kind "run" —
   * this service is the VERBS of a run's lifecycle only.
   *
   * @generated from rpc graphene.management.v1.RunsAPI.CancelRun
   */
  cancelRun: {
    methodKind: "unary";
    input: typeof CancelRunRequestSchema;
    output: typeof CancelRunResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_management_v1_runs, 0);

