// @generated by protoc-gen-es v2.14.0 with parameter "target=ts"
// @generated from file proto/management/v1/secrets.proto (package graphene.management.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/management/v1/secrets.proto.
 */
export const file_proto_management_v1_secrets: GenFile = /*@__PURE__*/
  fileDesc("CiFwcm90by9tYW5hZ2VtZW50L3YxL3NlY3JldHMucHJvdG8SFmdyYXBoZW5lLm1hbmFnZW1lbnQudjEiLwoQU2V0U2VjcmV0UmVxdWVzdBIMCgRuYW1lGAEgASgJEg0KBXZhbHVlGAIgASgJIiQKEVNldFNlY3JldFJlc3BvbnNlEg8KB3ZlcnNpb24YASABKAUybgoKU2VjcmV0c0FQSRJgCglTZXRTZWNyZXQSKC5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLlNldFNlY3JldFJlcXVlc3QaKS5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLlNldFNlY3JldFJlc3BvbnNlQkZaRGdpdGh1Yi5jb20vZ3JhcGhlbmUtY2kvZ3JhcGhlbmUvcGtnL3Byb3RvL21hbmFnZW1lbnQvdjE7bWFuYWdlbWVudHYxYgZwcm90bzM");

/**
 * @generated from message graphene.management.v1.SetSecretRequest
 */
export type SetSecretRequest = Message<"graphene.management.v1.SetSecretRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string value = 2;
   */
  value: string;
};

/**
 * Describes the message graphene.management.v1.SetSecretRequest.
 * Use `create(SetSecretRequestSchema)` to create a new message.
 */
export const SetSecretRequestSchema: GenMessage<SetSecretRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_secrets, 0);

/**
 * @generated from message graphene.management.v1.SetSecretResponse
 */
export type SetSecretResponse = Message<"graphene.management.v1.SetSecretResponse"> & {
  /**
   * Version is what the record now counts: how many times this name
   * has been written.
   *
   * @generated from field: int32 version = 1;
   */
  version: number;
};

/**
 * Describes the message graphene.management.v1.SetSecretResponse.
 * Use `create(SetSecretResponseSchema)` to create a new message.
 */
export const SetSecretResponseSchema: GenMessage<SetSecretResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_secrets, 1);

/**
 * SecretsAPI is the one channel a secret VALUE travels: in, once, and
 * never back. Everything else about a secret — that the name exists,
 * who owns it, when it was last rotated, deleting it — is the ordinary
 * record of kind "secret", read and written through ResourcesAPI. The
 * value cannot ride a record's command: a command payload becomes a
 * history event, and a history is forever.
 *
 * @generated from service graphene.management.v1.SecretsAPI
 */
export const SecretsAPI: GenService<{
  /**
   * @generated from rpc graphene.management.v1.SecretsAPI.SetSecret
   */
  setSecret: {
    methodKind: "unary";
    input: typeof SetSecretRequestSchema;
    output: typeof SetSecretResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_management_v1_secrets, 0);

