// @generated by protoc-gen-es v2.14.0 with parameter "target=ts"
// @generated from file proto/management/v1/secrets.proto (package graphene.management.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/management/v1/secrets.proto.
 */
export const file_proto_management_v1_secrets: GenFile = /*@__PURE__*/
  fileDesc("CiFwcm90by9tYW5hZ2VtZW50L3YxL3NlY3JldHMucHJvdG8SFmdyYXBoZW5lLm1hbmFnZW1lbnQudjEiLwoQU2V0U2VjcmV0UmVxdWVzdBIMCgRuYW1lGAEgASgJEg0KBXZhbHVlGAIgASgJIhMKEVNldFNlY3JldFJlc3BvbnNlIiMKE0RlbGV0ZVNlY3JldFJlcXVlc3QSDAoEbmFtZRgBIAEoCSIWChREZWxldGVTZWNyZXRSZXNwb25zZSIUChJMaXN0U2VjcmV0c1JlcXVlc3QiJAoTTGlzdFNlY3JldHNSZXNwb25zZRINCgVuYW1lcxgBIAMoCTLBAgoKU2VjcmV0c0FQSRJgCglTZXRTZWNyZXQSKC5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLlNldFNlY3JldFJlcXVlc3QaKS5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLlNldFNlY3JldFJlc3BvbnNlEmkKDERlbGV0ZVNlY3JldBIrLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuRGVsZXRlU2VjcmV0UmVxdWVzdBosLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuRGVsZXRlU2VjcmV0UmVzcG9uc2USZgoLTGlzdFNlY3JldHMSKi5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLkxpc3RTZWNyZXRzUmVxdWVzdBorLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuTGlzdFNlY3JldHNSZXNwb25zZUJGWkRnaXRodWIuY29tL2dyYXBoZW5lLWNpL2dyYXBoZW5lL3BrZy9wcm90by9tYW5hZ2VtZW50L3YxO21hbmFnZW1lbnR2MWIGcHJvdG8z");

/**
 * @generated from message graphene.management.v1.SetSecretRequest
 */
export type SetSecretRequest = Message<"graphene.management.v1.SetSecretRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string value = 2;
   */
  value: string;
};

/**
 * Describes the message graphene.management.v1.SetSecretRequest.
 * Use `create(SetSecretRequestSchema)` to create a new message.
 */
export const SetSecretRequestSchema: GenMessage<SetSecretRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_secrets, 0);

/**
 * @generated from message graphene.management.v1.SetSecretResponse
 */
export type SetSecretResponse = Message<"graphene.management.v1.SetSecretResponse"> & {
};

/**
 * Describes the message graphene.management.v1.SetSecretResponse.
 * Use `create(SetSecretResponseSchema)` to create a new message.
 */
export const SetSecretResponseSchema: GenMessage<SetSecretResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_secrets, 1);

/**
 * @generated from message graphene.management.v1.DeleteSecretRequest
 */
export type DeleteSecretRequest = Message<"graphene.management.v1.DeleteSecretRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message graphene.management.v1.DeleteSecretRequest.
 * Use `create(DeleteSecretRequestSchema)` to create a new message.
 */
export const DeleteSecretRequestSchema: GenMessage<DeleteSecretRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_secrets, 2);

/**
 * @generated from message graphene.management.v1.DeleteSecretResponse
 */
export type DeleteSecretResponse = Message<"graphene.management.v1.DeleteSecretResponse"> & {
};

/**
 * Describes the message graphene.management.v1.DeleteSecretResponse.
 * Use `create(DeleteSecretResponseSchema)` to create a new message.
 */
export const DeleteSecretResponseSchema: GenMessage<DeleteSecretResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_secrets, 3);

/**
 * @generated from message graphene.management.v1.ListSecretsRequest
 */
export type ListSecretsRequest = Message<"graphene.management.v1.ListSecretsRequest"> & {
};

/**
 * Describes the message graphene.management.v1.ListSecretsRequest.
 * Use `create(ListSecretsRequestSchema)` to create a new message.
 */
export const ListSecretsRequestSchema: GenMessage<ListSecretsRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_secrets, 4);

/**
 * @generated from message graphene.management.v1.ListSecretsResponse
 */
export type ListSecretsResponse = Message<"graphene.management.v1.ListSecretsResponse"> & {
  /**
   * Names only — a value never travels back.
   *
   * @generated from field: repeated string names = 1;
   */
  names: string[];
};

/**
 * Describes the message graphene.management.v1.ListSecretsResponse.
 * Use `create(ListSecretsResponseSchema)` to create a new message.
 */
export const ListSecretsResponseSchema: GenMessage<ListSecretsResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_secrets, 5);

/**
 * SecretsAPI administers the namespace's secret set. VALUES go in and
 * never come out through this plane: workers resolve them at the point
 * of use through the worker plane; the management plane sees names.
 *
 * @generated from service graphene.management.v1.SecretsAPI
 */
export const SecretsAPI: GenService<{
  /**
   * @generated from rpc graphene.management.v1.SecretsAPI.SetSecret
   */
  setSecret: {
    methodKind: "unary";
    input: typeof SetSecretRequestSchema;
    output: typeof SetSecretResponseSchema;
  },
  /**
   * @generated from rpc graphene.management.v1.SecretsAPI.DeleteSecret
   */
  deleteSecret: {
    methodKind: "unary";
    input: typeof DeleteSecretRequestSchema;
    output: typeof DeleteSecretResponseSchema;
  },
  /**
   * @generated from rpc graphene.management.v1.SecretsAPI.ListSecrets
   */
  listSecrets: {
    methodKind: "unary";
    input: typeof ListSecretsRequestSchema;
    output: typeof ListSecretsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_management_v1_secrets, 0);

