// @generated by protoc-gen-es v2.14.0 with parameter "target=ts"
// @generated from file proto/management/v1/source.proto (package graphene.management.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/management/v1/source.proto.
 */
export const file_proto_management_v1_source: GenFile = /*@__PURE__*/
  fileDesc("CiBwcm90by9tYW5hZ2VtZW50L3YxL3NvdXJjZS5wcm90bxIWZ3JhcGhlbmUubWFuYWdlbWVudC52MSI6ChNVcGxvYWRTb3VyY2VSZXF1ZXN0EhMKC3BpcGVsaW5lX2lkGAEgASgJEg4KBnNvdXJjZRgCIAEoDCI4ChRVcGxvYWRTb3VyY2VSZXNwb25zZRIQCghsb2NhdGlvbhgBIAEoCRIOCgZkaWdlc3QYAiABKAkiJwoVRG93bmxvYWRTb3VyY2VSZXF1ZXN0Eg4KBnNvdXJjZRgBIAEoCSIjChNEb3dubG9hZFNvdXJjZUNodW5rEgwKBGRhdGEYASABKAwiFQoTTGlzdFJ1bnRpbWVzUmVxdWVzdCKrAQoUTGlzdFJ1bnRpbWVzUmVzcG9uc2USRgoIcnVudGltZXMYASADKAsyNC5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLkxpc3RSdW50aW1lc1Jlc3BvbnNlLlJ1bnRpbWUaSwoHUnVudGltZRIMCgRuYW1lGAEgASgJEg8KB3ZlcnNpb24YAiABKAkSDQoFaW1hZ2UYAyABKAkSEgoKaXNfZGVmYXVsdBgEIAEoCCIiChBMaXN0RmlsZXNSZXF1ZXN0Eg4KBnNvdXJjZRgBIAEoCSKLAQoRTGlzdEZpbGVzUmVzcG9uc2USPQoFZmlsZXMYASADKAsyLi5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLkxpc3RGaWxlc1Jlc3BvbnNlLkZpbGUSEwoLdHJlZV9kaWdlc3QYAiABKAkaIgoERmlsZRIMCgRwYXRoGAEgASgJEgwKBHNpemUYAiABKAMiLwoPUmVhZEZpbGVSZXF1ZXN0Eg4KBnNvdXJjZRgBIAEoCRIMCgRwYXRoGAIgASgJIiMKEFJlYWRGaWxlUmVzcG9uc2USDwoHY29udGVudBgBIAEoDDKSBAoJU291cmNlQVBJEmkKDFVwbG9hZFNvdXJjZRIrLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuVXBsb2FkU291cmNlUmVxdWVzdBosLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuVXBsb2FkU291cmNlUmVzcG9uc2USbgoORG93bmxvYWRTb3VyY2USLS5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLkRvd25sb2FkU291cmNlUmVxdWVzdBorLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuRG93bmxvYWRTb3VyY2VDaHVuazABEmkKDExpc3RSdW50aW1lcxIrLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuTGlzdFJ1bnRpbWVzUmVxdWVzdBosLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuTGlzdFJ1bnRpbWVzUmVzcG9uc2USYAoJTGlzdEZpbGVzEiguZ3JhcGhlbmUubWFuYWdlbWVudC52MS5MaXN0RmlsZXNSZXF1ZXN0GikuZ3JhcGhlbmUubWFuYWdlbWVudC52MS5MaXN0RmlsZXNSZXNwb25zZRJdCghSZWFkRmlsZRInLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuUmVhZEZpbGVSZXF1ZXN0GiguZ3JhcGhlbmUubWFuYWdlbWVudC52MS5SZWFkRmlsZVJlc3BvbnNlQkZaRGdpdGh1Yi5jb20vZ3JhcGhlbmUtY2kvZ3JhcGhlbmUvcGtnL3Byb3RvL21hbmFnZW1lbnQvdjE7bWFuYWdlbWVudHYxYgZwcm90bzM");

/**
 * @generated from message graphene.management.v1.UploadSourceRequest
 */
export type UploadSourceRequest = Message<"graphene.management.v1.UploadSourceRequest"> & {
  /**
   * Pipeline the uploaded tree is meant for; the upload area is per
   * pipeline, and a revision materialization builds from it.
   *
   * @generated from field: string pipeline_id = 1;
   */
  pipelineId: string;

  /**
   * The tree as tar.gz.
   *
   * @generated from field: bytes source = 2;
   */
  source: Uint8Array;
};

/**
 * Describes the message graphene.management.v1.UploadSourceRequest.
 * Use `create(UploadSourceRequestSchema)` to create a new message.
 */
export const UploadSourceRequestSchema: GenMessage<UploadSourceRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_source, 0);

/**
 * @generated from message graphene.management.v1.UploadSourceResponse
 */
export type UploadSourceResponse = Message<"graphene.management.v1.UploadSourceResponse"> & {
  /**
   * Location is where the tree was stored; a declaration or a sync
   * command carries this reference instead of the bytes.
   *
   * @generated from field: string location = 1;
   */
  location: string;

  /**
   * @generated from field: string digest = 2;
   */
  digest: string;
};

/**
 * Describes the message graphene.management.v1.UploadSourceResponse.
 * Use `create(UploadSourceResponseSchema)` to create a new message.
 */
export const UploadSourceResponseSchema: GenMessage<UploadSourceResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_source, 1);

/**
 * @generated from message graphene.management.v1.DownloadSourceRequest
 */
export type DownloadSourceRequest = Message<"graphene.management.v1.DownloadSourceRequest"> & {
  /**
   * @generated from field: string source = 1;
   */
  source: string;
};

/**
 * Describes the message graphene.management.v1.DownloadSourceRequest.
 * Use `create(DownloadSourceRequestSchema)` to create a new message.
 */
export const DownloadSourceRequestSchema: GenMessage<DownloadSourceRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_source, 2);

/**
 * @generated from message graphene.management.v1.DownloadSourceChunk
 */
export type DownloadSourceChunk = Message<"graphene.management.v1.DownloadSourceChunk"> & {
  /**
   * @generated from field: bytes data = 1;
   */
  data: Uint8Array;
};

/**
 * Describes the message graphene.management.v1.DownloadSourceChunk.
 * Use `create(DownloadSourceChunkSchema)` to create a new message.
 */
export const DownloadSourceChunkSchema: GenMessage<DownloadSourceChunk> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_source, 3);

/**
 * @generated from message graphene.management.v1.ListRuntimesRequest
 */
export type ListRuntimesRequest = Message<"graphene.management.v1.ListRuntimesRequest"> & {
};

/**
 * Describes the message graphene.management.v1.ListRuntimesRequest.
 * Use `create(ListRuntimesRequestSchema)` to create a new message.
 */
export const ListRuntimesRequestSchema: GenMessage<ListRuntimesRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_source, 4);

/**
 * @generated from message graphene.management.v1.ListRuntimesResponse
 */
export type ListRuntimesResponse = Message<"graphene.management.v1.ListRuntimesResponse"> & {
  /**
   * @generated from field: repeated graphene.management.v1.ListRuntimesResponse.Runtime runtimes = 1;
   */
  runtimes: ListRuntimesResponse_Runtime[];
};

/**
 * Describes the message graphene.management.v1.ListRuntimesResponse.
 * Use `create(ListRuntimesResponseSchema)` to create a new message.
 */
export const ListRuntimesResponseSchema: GenMessage<ListRuntimesResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_source, 5);

/**
 * @generated from message graphene.management.v1.ListRuntimesResponse.Runtime
 */
export type ListRuntimesResponse_Runtime = Message<"graphene.management.v1.ListRuntimesResponse.Runtime"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string version = 2;
   */
  version: string;

  /**
   * @generated from field: string image = 3;
   */
  image: string;

  /**
   * @generated from field: bool is_default = 4;
   */
  isDefault: boolean;
};

/**
 * Describes the message graphene.management.v1.ListRuntimesResponse.Runtime.
 * Use `create(ListRuntimesResponse_RuntimeSchema)` to create a new message.
 */
export const ListRuntimesResponse_RuntimeSchema: GenMessage<ListRuntimesResponse_Runtime> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_source, 5, 0);

/**
 * @generated from message graphene.management.v1.ListFilesRequest
 */
export type ListFilesRequest = Message<"graphene.management.v1.ListFilesRequest"> & {
  /**
   * @generated from field: string source = 1;
   */
  source: string;
};

/**
 * Describes the message graphene.management.v1.ListFilesRequest.
 * Use `create(ListFilesRequestSchema)` to create a new message.
 */
export const ListFilesRequestSchema: GenMessage<ListFilesRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_source, 6);

/**
 * @generated from message graphene.management.v1.ListFilesResponse
 */
export type ListFilesResponse = Message<"graphene.management.v1.ListFilesResponse"> & {
  /**
   * @generated from field: repeated graphene.management.v1.ListFilesResponse.File files = 1;
   */
  files: ListFilesResponse_File[];

  /**
   * @generated from field: string tree_digest = 2;
   */
  treeDigest: string;
};

/**
 * Describes the message graphene.management.v1.ListFilesResponse.
 * Use `create(ListFilesResponseSchema)` to create a new message.
 */
export const ListFilesResponseSchema: GenMessage<ListFilesResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_source, 7);

/**
 * @generated from message graphene.management.v1.ListFilesResponse.File
 */
export type ListFilesResponse_File = Message<"graphene.management.v1.ListFilesResponse.File"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * @generated from field: int64 size = 2;
   */
  size: bigint;
};

/**
 * Describes the message graphene.management.v1.ListFilesResponse.File.
 * Use `create(ListFilesResponse_FileSchema)` to create a new message.
 */
export const ListFilesResponse_FileSchema: GenMessage<ListFilesResponse_File> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_source, 7, 0);

/**
 * @generated from message graphene.management.v1.ReadFileRequest
 */
export type ReadFileRequest = Message<"graphene.management.v1.ReadFileRequest"> & {
  /**
   * @generated from field: string source = 1;
   */
  source: string;

  /**
   * @generated from field: string path = 2;
   */
  path: string;
};

/**
 * Describes the message graphene.management.v1.ReadFileRequest.
 * Use `create(ReadFileRequestSchema)` to create a new message.
 */
export const ReadFileRequestSchema: GenMessage<ReadFileRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_source, 8);

/**
 * @generated from message graphene.management.v1.ReadFileResponse
 */
export type ReadFileResponse = Message<"graphene.management.v1.ReadFileResponse"> & {
  /**
   * @generated from field: bytes content = 1;
   */
  content: Uint8Array;
};

/**
 * Describes the message graphene.management.v1.ReadFileResponse.
 * Use `create(ReadFileResponseSchema)` to create a new message.
 */
export const ReadFileResponseSchema: GenMessage<ReadFileResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_source, 9);

/**
 * SourceAPI is the BYTES side of a source. A source is an ordinary
 * record — a gitsource, declared with Apply, synced with Invoke, read
 * with Get — so what stays here is only what a command cannot carry:
 * file content, and questions about the installation rather than about
 * a record.
 *
 * Every request names a source as "kind/id" ("gitsource/main"). Files
 * of a gitsource are readable and not writable: it is a checkout of a
 * commit, and writing into it would fork the project silently.
 *
 * @generated from service graphene.management.v1.SourceAPI
 */
export const SourceAPI: GenService<{
  /**
   * UploadSource stores a source tree and returns its reference. Bytes
   * do not travel in commands: a command's payload becomes an event in
   * the record's history, and a source tree would bury it.
   *
   * @generated from rpc graphene.management.v1.SourceAPI.UploadSource
   */
  uploadSource: {
    methodKind: "unary";
    input: typeof UploadSourceRequestSchema;
    output: typeof UploadSourceResponseSchema;
  },
  /**
   * DownloadSource hands back the pipeline's current working tree.
   *
   * @generated from rpc graphene.management.v1.SourceAPI.DownloadSource
   */
  downloadSource: {
    methodKind: "server_streaming";
    input: typeof DownloadSourceRequestSchema;
    output: typeof DownloadSourceChunkSchema;
  },
  /**
   * ListRuntimes answers "which languages can I write a pipeline in
   * on THIS installation".
   *
   * @generated from rpc graphene.management.v1.SourceAPI.ListRuntimes
   */
  listRuntimes: {
    methodKind: "unary";
    input: typeof ListRuntimesRequestSchema;
    output: typeof ListRuntimesResponseSchema;
  },
  /**
   * The tree is READ-ONLY: Studio lists and reads files of a checkout;
   * a source follows its ref and is never written into.
   *
   * @generated from rpc graphene.management.v1.SourceAPI.ListFiles
   */
  listFiles: {
    methodKind: "unary";
    input: typeof ListFilesRequestSchema;
    output: typeof ListFilesResponseSchema;
  },
  /**
   * @generated from rpc graphene.management.v1.SourceAPI.ReadFile
   */
  readFile: {
    methodKind: "unary";
    input: typeof ReadFileRequestSchema;
    output: typeof ReadFileResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_management_v1_source, 0);

