// @generated by protoc-gen-es v2.14.0 with parameter "target=ts"
// @generated from file proto/management/v1/vars.proto (package graphene.management.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/management/v1/vars.proto.
 */
export const file_proto_management_v1_vars: GenFile = /*@__PURE__*/
  fileDesc("Ch5wcm90by9tYW5hZ2VtZW50L3YxL3ZhcnMucHJvdG8SFmdyYXBoZW5lLm1hbmFnZW1lbnQudjEiLAoNU2V0VmFyUmVxdWVzdBIMCgRuYW1lGAEgASgJEg0KBXZhbHVlGAIgASgJIhAKDlNldFZhclJlc3BvbnNlIiAKEERlbGV0ZVZhclJlcXVlc3QSDAoEbmFtZRgBIAEoCSITChFEZWxldGVWYXJSZXNwb25zZSIRCg9MaXN0VmFyc1JlcXVlc3QicgoQTGlzdFZhcnNSZXNwb25zZRI6CgR2YXJzGAEgAygLMiwuZ3JhcGhlbmUubWFuYWdlbWVudC52MS5MaXN0VmFyc1Jlc3BvbnNlLlZhchoiCgNWYXISDAoEbmFtZRgBIAEoCRINCgV2YWx1ZRgCIAEoCTKjAgoHVmFyc0FQSRJXCgZTZXRWYXISJS5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLlNldFZhclJlcXVlc3QaJi5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLlNldFZhclJlc3BvbnNlEmAKCURlbGV0ZVZhchIoLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuRGVsZXRlVmFyUmVxdWVzdBopLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuRGVsZXRlVmFyUmVzcG9uc2USXQoITGlzdFZhcnMSJy5ncmFwaGVuZS5tYW5hZ2VtZW50LnYxLkxpc3RWYXJzUmVxdWVzdBooLmdyYXBoZW5lLm1hbmFnZW1lbnQudjEuTGlzdFZhcnNSZXNwb25zZUJGWkRnaXRodWIuY29tL2dyYXBoZW5lLWNpL2dyYXBoZW5lL3BrZy9wcm90by9tYW5hZ2VtZW50L3YxO21hbmFnZW1lbnR2MWIGcHJvdG8z");

/**
 * @generated from message graphene.management.v1.SetVarRequest
 */
export type SetVarRequest = Message<"graphene.management.v1.SetVarRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string value = 2;
   */
  value: string;
};

/**
 * Describes the message graphene.management.v1.SetVarRequest.
 * Use `create(SetVarRequestSchema)` to create a new message.
 */
export const SetVarRequestSchema: GenMessage<SetVarRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_vars, 0);

/**
 * @generated from message graphene.management.v1.SetVarResponse
 */
export type SetVarResponse = Message<"graphene.management.v1.SetVarResponse"> & {
};

/**
 * Describes the message graphene.management.v1.SetVarResponse.
 * Use `create(SetVarResponseSchema)` to create a new message.
 */
export const SetVarResponseSchema: GenMessage<SetVarResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_vars, 1);

/**
 * @generated from message graphene.management.v1.DeleteVarRequest
 */
export type DeleteVarRequest = Message<"graphene.management.v1.DeleteVarRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message graphene.management.v1.DeleteVarRequest.
 * Use `create(DeleteVarRequestSchema)` to create a new message.
 */
export const DeleteVarRequestSchema: GenMessage<DeleteVarRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_vars, 2);

/**
 * @generated from message graphene.management.v1.DeleteVarResponse
 */
export type DeleteVarResponse = Message<"graphene.management.v1.DeleteVarResponse"> & {
};

/**
 * Describes the message graphene.management.v1.DeleteVarResponse.
 * Use `create(DeleteVarResponseSchema)` to create a new message.
 */
export const DeleteVarResponseSchema: GenMessage<DeleteVarResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_vars, 3);

/**
 * @generated from message graphene.management.v1.ListVarsRequest
 */
export type ListVarsRequest = Message<"graphene.management.v1.ListVarsRequest"> & {
};

/**
 * Describes the message graphene.management.v1.ListVarsRequest.
 * Use `create(ListVarsRequestSchema)` to create a new message.
 */
export const ListVarsRequestSchema: GenMessage<ListVarsRequest> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_vars, 4);

/**
 * @generated from message graphene.management.v1.ListVarsResponse
 */
export type ListVarsResponse = Message<"graphene.management.v1.ListVarsResponse"> & {
  /**
   * @generated from field: repeated graphene.management.v1.ListVarsResponse.Var vars = 1;
   */
  vars: ListVarsResponse_Var[];
};

/**
 * Describes the message graphene.management.v1.ListVarsResponse.
 * Use `create(ListVarsResponseSchema)` to create a new message.
 */
export const ListVarsResponseSchema: GenMessage<ListVarsResponse> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_vars, 5);

/**
 * @generated from message graphene.management.v1.ListVarsResponse.Var
 */
export type ListVarsResponse_Var = Message<"graphene.management.v1.ListVarsResponse.Var"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string value = 2;
   */
  value: string;
};

/**
 * Describes the message graphene.management.v1.ListVarsResponse.Var.
 * Use `create(ListVarsResponse_VarSchema)` to create a new message.
 */
export const ListVarsResponse_VarSchema: GenMessage<ListVarsResponse_Var> = /*@__PURE__*/
  messageDesc(file_proto_management_v1_vars, 5, 0);

/**
 * VarsAPI administers the namespace's VARIABLES — the visible sibling
 * of secrets: environment configuration (cloud folder ids, hosts) that
 * does not belong in pipeline code but is not sensitive. Params may
 * reference one as "${var:name}"; the door substitutes the value when
 * the run starts, before schema validation. Unlike secrets, values
 * read back.
 *
 * @generated from service graphene.management.v1.VarsAPI
 */
export const VarsAPI: GenService<{
  /**
   * @generated from rpc graphene.management.v1.VarsAPI.SetVar
   */
  setVar: {
    methodKind: "unary";
    input: typeof SetVarRequestSchema;
    output: typeof SetVarResponseSchema;
  },
  /**
   * @generated from rpc graphene.management.v1.VarsAPI.DeleteVar
   */
  deleteVar: {
    methodKind: "unary";
    input: typeof DeleteVarRequestSchema;
    output: typeof DeleteVarResponseSchema;
  },
  /**
   * @generated from rpc graphene.management.v1.VarsAPI.ListVars
   */
  listVars: {
    methodKind: "unary";
    input: typeof ListVarsRequestSchema;
    output: typeof ListVarsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_management_v1_vars, 0);

